= Site Maquette pour l'entreprise Samsung

== Prérequis
- https://www.php.net/downloads[PHP >= 7.4]
- https://symfony.com/doc/current/getting_started/index.html[Symfony]
- https://getcomposer.org/doc/00-intro.md[Composer]
- https://git-scm.com/downloads[Git]



== Accéder à la maquette 

Ouvrir un terminal

1) Cloner le repository :

[source]
-----
git clone https://github.com/omelette-watin/samsungmaquette.git
-----

2) Lancer l'un des fichiers .html dans /maquette

OU 

== Procédure pour lancer l'application Symfony :

Ouvrir un terminal

1) Cloner le repository :

[source]
-----
git clone https://github.com/omelette-watin/samsungmaquette.git
-----

2) Se diriger à la racine du projet et installer les requirements :

[source]
-----
composer install
-----

3) Créer la base de donnée :

[source]
-----
symfony console doctrine:database:create
-----

4) Effectuer les migrations :

[source]
-----
symfony console make:migration
-----

puis :

[source] 
-----
symfony console doctrine:migrations:migrate
-----

5) Peupler la base de donnée grâce aux data fixtures :

[source]
-----
symfony console doctrine:fixtures:load
-----

ou par une requête SQL :

[source]
-----
symfony console doctrine:query:sql "Votre requête sql"
-----

6) Lancer le serveur :

[source]
-----
symfony serve
-----

== Changer de type de database 

Nous avons décidé pour ce projet d'utiliser sqlite comme modèle de base de donnée. Nous sommes conscients que ce modèle est limité.
De fait si vous disposez d'une base de donnée autre (MySQL, Postgresql, etc.) il est tout à fait possible pour vous de la changer.

1) Modifier le fichier .env à la racine du projet :

- Commenter la ligne définissant l'actuelle base de donnée ("DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db")
- Décommenter la ligne définissant la base de donnée souhaitée et renseigner l'utilisateur, le mot de passe, l'adresse IP et la version

2) Reprenez les étapes liées à la base de données :

[source]
-----
symfony console doctrine:database:create
-----

[source]
-----
symfony console make:migration
-----

[source] 
-----
symfony console doctrine:migrations:migrate
-----

Sans oublier de peupler cette base de donnée !

[source]
-----
symfony console doctrine:fixtures:load
-----
